label first_day_laura:

    scene black with logodissolve_laura
    $ clock.psychename = ["LAURA"]
    $ clock.hourclock = 0
    show screen clock_marker with dissolve
    scene bg uni with fade
    p "..."
    p "(I can't stop thinking about what Miss Julia said to mom...)"
    p "(She looked very nervous. I wonder... I mean, I didn't even know they knew each other.)"
    p "(Mom... I never even thought that my mom could have any kind of secret. She have always been very loving.)"
    p "(But... Is she even involved in all this? Her mind was... Odd...)"
    show laura p41_sad with dissolve
    p "(I've been so invested in investating all the others that I never considered other people.)"
    l "[povname]...?"
    p "(Well... I guess it's worth a try, at the very least. I just don't want to waste a day in just that...)"
    l p41_surprised "[povname]?"
    p "(But I will...)"
    l p31_angry "[povname]!"
    p "Huh? MOM!?"
    l p21_sad "Are you alright? You looked like you were zoning out."
    p "I... Eh... Yeah mom, I was just thinking..."
    l "Be careful, baby, what if you tried to cross the street like that!?"
    p "Mom, I was just a bit distracted, I'm not that stupid, or suicidal."
    l p41_sad "If you say so..."
    p "(That's weird, mom is not being as cheerful as she usually is...)"
    p "(I wonder if there's something wrong.)"
    p "Mom, are you ok?"
    l p21_surprised "I eh..." with flash
    l p11_happy "Yes! Yes of course, baby! Why are you asking?"
    p "(She realized already, I guess, so... Let's try to push her to the direction I want to.)"
    p "Well, for starters, it's weird to see you around the campus, what are you doing here?"
    l p11_surprised "I..."
    l p11_happy "I was looking for you, of course!"
    p "..."
    p "(Mom... I think you are a very sweet person, but you are a terrible liar.)"
    p "Well, you needed something from me, then, mom?"
    l p31_sad "Truth is... I miss you, baby, why can't you go back home?"
    p "Mom... We don't have a home."
    l @ p31_surprised "...!"
    l "[povname], that's very cruel..."
    p "(Not again...)"
    p "Mom, I mean it, you live in an apartment like I do. Why don't you come live with me?"
    l @ p31_surprised "...!"
    p "(I honestly wouldn't like that, I'm happy living by myself.)"
    p "(But I can't deny, I guess mom gets lonely by herself...)"
    l "W-well... I can think about it but... You are a grown man now..."
    p "So?"
    l "I think you need space, baby. What if you have a girlfriend and..."
    l @ p31_surprised "...!" with flash
    l p41_sad "I didn't mean to..."
    p "What..."
    l "As I said, you must have lots of women behind you... Or... Even a single one."
    p "(Is she... Thinking about what happened with Miss Julia?)"
    l "[povname]... You should really come home..."
    p "({i}sigh{/i}... I don't really want to, but I feel really sorry for her now...)"
    p "(She must be annoyed and worried about what is happening, so at the very least I should go with her.)"
    p "(Not to mention is a perfect opportunity to set things straight and try to figure out more about this mess.)"
    p "Alright, mom."
    l p21_surprised "Ah...!?" with flash
    p "I'm going home with you."
    l "R-really!?"
    l p31_happy "Yes! Let's go baby!"
    p "Eh... I need to go to classes, mom."
    l p31_neutral "Ah... Of course of course! I'm sorry I... I'm just excited."
    p "Don't worry mom, today I can leave early so..."
    p "(There's a big probability she actually came here to see Julia. So...)"
    p "You should go home, I'll go there once I finish, ok?"
    l p11_happy "Alright! It's a promise, I'll make a nice meal for both of us, ok, honey?"
    l "I'll hurry back home! See ya in a bit!"
    hide laura with dissolve
    p "..."
    p "(There she goes... She is certainly very excited about this...)"
    p "(Is my mom really involved in all of this? She just seems to be worried.)"
    p "(Well, nothing to do about it right now, I'll just go on my day until it's time to go to our old apartment.)"
    scene black with fade
    $ clock.advance_hour()
    "The day went by without anything particularly interesting going."
    scene bg uni_hall with fade
    p "Time to head to my mom's apartment..."
    scene bg laura_hall with fade
    p "(I know it's rude to just enter, but I still have the key, no need to wait outside at all.)"
    p "Mom? Are you a..."
    show laura p13_serious with dissolve
    p "... round...?"
    l p33_surprised "[povname]! W-what are you doing here!?"
    p "What are YOU doing going around naked through the house!?"
    l "I was cooking!"
    p "Who cooks naked!?"
    l "I live by myself! I never had any problem with that before!"
    l "I... I should get changed!"
    hide laura with dissolve
    p "Alright, that was awkward..."
    p "But despite her age, mom does have a great body."
    p "... And that's something wrong to think about it. Oh well..."
    scene black with fade
    "Mom took her time getting changed, I had to finish the meal she was cooking myself because of it and served everything."
    scene bg laura_hall with fade
    show laura p41_sad with dissolve
    l "Hey, [povname]..."
    p "Ah... Mom, don't worry, it's ok, it was an accident, sorry I didn't knock on the door first."
    l "It's okay, baby, I forgot you have a key yourself... I was just very comfortable..."
    l p21_serious "Besides, it's not like you saw something you have not seen before..."
    p "(Well, it's true that when we lived together, mom actually never had any problem being naked around me.)"
    p "(But that was yeard ago, I think now is still awkward, for both of us.)"
    l p21_surprised "Ah! The food! I'm sorry I-"
    p "It's ok, mom, it's already done."
    l "You... Finished the food already?"
    l "Baby, you don't even know how to cook!"
    p "Mom... I had to learn how to, I live by myself, what did you expect from me?"
    l p21_serious "That you only ate junk food or something..."
    p "Not at all, mom, junk food is actually very expensive, and I had to learn at least the basics."
    p "You'd be surprised how easy it is to prepare a decent meal with very few stuff, mainly vegetables."
    l p21_surprised "Ah, you added some vegetables to the pasta...!"
    l p31_happy "That's amazing, baby!"
    p "Ah... Mom, it's nothing, really, is a very basic meal, as I said."
    l p41_sad "..."
    p "Besides, maybe later you can cook, I do miss your food."
    l p41_surprised "...!"
    l p11_happy "Of course, baby! I'd love to! But..."
    l p11_neutral "But for now, we should eat this, I'm dying to taste your own food, baby."
    scene black with fade
    "She sat down in front of me and we bagan to eat."
    "Her face lighten up a bit."
    scene lauraextra101 with dissolve
    l "Wow! This is amazing! You are such a good cook!"
    p "Technically half of it was already done, mom, I just sautéed the vegetables, mom."
    l "Sautéed? That's very refined! You have learned a lot!"
    p "Sounds like it, but it's basically just frying the vegetables."
    p "The efectiveness varies depending on the person preparing it. Professional chefs can make flames and everything."
    l "Isn't that dangerous?"
    p "It kinda is. I don't even know how to do it, so it's now like I'm that much of a good chef."
    l "It's still pretty amazing baby. As it is now, I bet your future wife would be happy!"
    scene lauraextra102 with dissolve
    p "Hm?"
    p "(As soon as she said that, she got a bit gloomy.)"
    p "Are you ok, mom?"
    l "Yeah... I was just thinking... Baby, do you plan on getting a girlfriend?"
    l "You are growing like a nice young man. I bet you are popular among the ladies."
    p "(Not exactly, I don't have a lot of problems in that regard, but I have other things to focus on.)"
    p "Well, I've had a girlfriend before, mom."
    l "Do you plan on marrying someone in particular?"
    p "Not quite. As I said, I had girlfriend before, mom, but... I have more things to think about."
    l "... What kind of woman do you like?"
    p "I don't really have an specific type of woman, mom. I mean, someone nice, I guess?"
    p "(That's a bit lame, but it's also true, I could have said something else, but... These questions are very embarrassing.)"
    l "Do you like... Do you like older women?"
    p "Hm?"
    scene lauraextra101 with dissolve
    l "Nevermind, it's getting very personal, isn't it, baby? Hehehe."
    scene lauraextra102 with dissolve
    p "(And so, she went back to being gloomy.)"
    p "(It's very evident that she is worried about Miss Julia...)"
    p "(This may be my opportunity to set things straight with my mom, so I'll be direct.)"
    p "Mom... I think... I think Miss Julia have told you a couple of things about me, isn't it?"
    scene lauraextra103 with flash
    l "...!"
    p "It... It isn't what you think, really, but I need to ask you a couple of things first."
    l "..."
    p "First I need to know, what is your relationship with Miss Julia?"
    l "..."
    p "Mom...?"
    p "I just need to know, I didn't even know you guys knew each other."
    l "I... I have a question first."
    p "...?"
    scene lauraextra102 with dissolve
    l "Are you... Are you really having sex with her?"
    p "..."
    p "Yes mom, I actually have."
    scene lauraextra103 with dissolve
    l "..."
    l "I... I see..."
    p "(Hm? No reaction from her, at least not the kind of reaction I expected...)"
    p "(I guess it's not such a surprise because Miss Julia have been telling her everything.)"
    scene lauraextra102 with dissolve
    l "..."
    p "Mom, can you answer my questions?"
    l "..."
    p "Are you ok, mom? I will explain everything really, I just-"
    scene lauraextra104 with dissolve
    l "Hehe, don't worry baby. I'm just worried, I wanted to know if it was true that's all."
    l "But we shouldn't be talking about these kind of things right now, I think."
    l "I mean, you came back home after so much time and we are enjoying this nice food!"
    p "... I guess you are right."
    scene lauraextra105 with dissolve
    l "And as you said, you can explain everything, but not right now, ok? Maybe next time you come?"
    p "Alright, mom..."
    scene black with fade
    "We kept eating mostly in silence, she tried bringing up stuff from my chidhood."
    "I didn't ignore her, but... I was thinking about her relationship with Miss Julia."
    "She very much ignored it on purpose, and she have been fidgeting ever since."
label laura_scene1:
    scene bg laura_hall with fade
    $ clock.advance_hour()
    show laura p11_neutral with dissolve
    l "[povname], can you wait for me here, please?"
    p "Hm? Sure mom. Although, I probably should leave in a while."
    l "I won't take long, I promise, I just need to do something in my room."
    hide laura p11_neutral with dissolve
    p "(Well, that's not suspicious at all...)"
    p "(It's very evident that mom is upset. She is kind of annoying, but I don't want her to worry...)"
    scene black with fade
    "Mom didn't take long as she promised, but, when she came by, she was silent and looking at the floor."
    scene bg laura_hall with fade
    show laura p41_sad with dissolve
    p "Mom? Are you ok? Do you want to talk about-"
    "As soon as I mentioned that, she reacted and sat next to me in a really strange way."
    scene laura101 with dissolve
    "She was exposing her thighs that now had lingerie and was still looking down."
    p "Mom...?"
    l "... [povname], are you sure that you... Don't have an specific kind of woman?"
    p "...?"
    l "I'm a mature woman, [povname]. I had you, after all."
    l "Do you think... Do you think I'm attractive?"
    p "...? Mom...?"
    "Everything was twisting around me, what was mom trying to go to?"
    scene laura102 with dissolve
    l "Am I at least more attractive than Julia?"
    p "...!"
    l "I just want to know, I mean, I know Julia takes more care of herself."
    l "We are the same age but her body is obviously more attractive than mine, isn't it?"
    l "I barely take care of myself and I bet I have more fat than she does, but..."
    l "But you don't need to go to her in order to satisfy yourself, [povname]."
    p "... W-what do you mean...?"
    l "I mean... I mean that your mom is right here, after all."
    "She blushed heabily as soon as she said that."
    "Is mom really saying what I think she is?"
    scene laura103 with dissolve
    "She stood and was looking ever so nervous."
    p "M-mom, what are you doing?"
    l "Did you like what you saw when you got here? I... I liked it, myself."
    p "...!"
    l "I know, I must look like a pervert, but... I can even tell from here that you like it too."
    "She was right, I have a boner already, and a very big one, just from thinking about that?"
    l "So... I guess you like it. Maybe not as much as Julia, but even if I'm not as attractive..."
    l "I can do other things, you know...?"
    p "Mom... This... This is wrong, you should-"
    scene laura104 with dissolve
    l "So... How are them? My breasts, I mean."
    l "I know I'm only showing you my bra, but I'm a bit ashamed, whenever I take my bra off..."
    l "Well, it doesn't matter, you are my son, I shouldn't be embarrassed in front of you."
    p "(You shouldn't be doing this either, mom!)"
    l "So, be honest, baby, what do you think? Are they attractive? What about my belly?"
    l "It's embarrassing to ask, so please... Be honest, ok?"
    "Again, I felt things twisting around me, and yet dick was reacting heavily."
    "And then I started talking without even thinking."
    p "You look sexy, mom... Your waist and your belly are very nice."
    p "And your breasts are actually... They are actually very big."
    l "You like that?"
    p "Yeah..."
    l "Then..."
    scene laura105 with dissolve
    l "What about this? You like it too?"
    p "...!"
    "It was very sudden and I could feel a shiver down my spine."
    l "I... I don't usually wear these kind of things. But the truth is, I really like to..."
    l "I have no one to show them to, though, so I'm a little nervous, but how is it, [povname]?"
    l "Do you like lingerie? Do you like my body?"
    p "..."
    "I was mesmerized watching a very specific point in mom..."
    "I was looking at the outline of her pussy in her underwear."
    "The colors were arranged almost as if that's the specific point she wants me to look at."
    "The straps were shaping her soft thighs, and also shapes a part of her socks."
    "I'm sure that has a name, but for the life of me I can't even remember that now."
    "It was just my mom there showing me her underwear and me getting this huge boner."
    l "[povname]...? Baby...?"
    p "I... I just..."
    l "...!"
    l "Don't worry, I see where you are looking at now..."
    l "And honestly, I don't mind... It even feels better, even my... Even my pussy is tingling."
    p "...!"
    l "So... Do you want to see? Come to think of it, I don't think you are looking as good as you could..."
    l "So... What about this?"
    scene laura106 with dissolve
    "She turned around showing me her bare ass..."
    p "If I'm honest, it's even bigger than Miss Julia's."
    l "...! T-thanks, baby..."
    p "...!"
    "When I realized I said that outloud it was too late, but... She seems to be glad about it."
    l "What about my pussy? Does it look good? Do you like it?"
    p "I... Yeah mom, It's... It's very nice."
    "I thought about getting up and ram her right then and there, even if I think that's wrong."
    "But even if I didn't, I couldn't stand up..."
    "Things were spinning even more, actually, I thought it was the shock from the moment, but..."
    p "Mom... I... I'm getting... I'm dizzy."
    l "...! Are you ok, baby?"
    p "Maybe there was way too much blood flowing to my dick, but the truth is..."
    p "Mom..."
    scene black with fade
    "I suddenly fainted. I have no idea why. It wasn't because of the watch this time, was it...?"
    "Nonetheless, everything was blck for a moment, and at the next instant."
    scene laura107 with fade
    l "Baby...!?"
    l "Are you alright!?"
    p "Mom...? What happened...?"
    l "You fainted, baby... Are you ok?"
    p "I... I think so, mom, I just have 3 questions..."
    l "Yeah baby, what is it?"
    p "Why am I naked? What happened to your top, and why is my dick hard?"
    l "Ah... Eh... That... Well... Eh..."
    l "I read somewhere that when you faint, it's... It's better to take your clothes off."
    p "..."
    l "And I was so nervous, I got really worked up, so I took off my sweater."
    p "And...?"
    l "And... And... Well, you were still hard and I... I..."
    scene laura108 with dissolve
    l "I just kept playing with your cock! I mean, look at it, baby!"
    l "You are seriously packing! I was worried about you! And and...!"
    l "I thought it could help, and well, you were always still hard!"
    l "And I couldn't stop... Not even now."
    scene laura107 with dissolve
    l "I'm sorry, [povname]... You must think I'm a big pervert for doing this..."
    l "But I mean it, your mom is here for you... So..."
    scene laura108 with dissolve
    l "So... Julia..."
    p "Mom... I get it."
    scene laura107 with dissolve
    l "Ah...?"
    p "Listen mom, I told you before, it isn't what-"
    "I think she stopped listening to me as soon as I said I get it."
    scene laura109 with dissolve
    "She was looking at me differently. I didn't dislike it, but it was very different."
    "She was looking right at me as she was holding my dick."
    l "I get it, baby. Then... Then I'll keep you busy... And..."
    scene laura110 with dissolve
    p "...!"
    "She moved her hand through my dick and started jacking me off."
    scene laura109 with dissolve
    "It was very sudden, and she looked directly at my eyes as she did it."
    "It felt unreal, I couldn't look anywhere else but at her tender eyes."
    scene laura110 with dissolve
    "But at the same time, it was undeniable my own mother was clumsily jacking me off."
    l "H-how is it, baby? Does it feel good? I must admit..."
    scene laura109 with dissolve
    l "Your cock is unbelievably hot and hard. You must think your mom is some kinf of nympho."
    p "(Now that you mention it...)"
    scene laura110 with dissolve
    l "The truth is... Any woman would hardly be able to contain herself after looking at it."
    l "Not only that, you are so young and handsome... I'm not ashamed to admit this myself..."
    scene laura109 with dissolve
    l "Even though I'm your mom, I'm also a woman, and as a woman I can say, you are perfect, baby."
    p "(You probably only say that because you are my mother... I think?)"
    scene laura110 with dissolve
    "If something, my mom seemed more invested in her handjob, looking at me with a growing desire."
    l "Baby... I don't think I will even be able to stop now, no matter what."
    scene laura109 with dissolve
    l "I want it, please cum..."
    scene laura110 with dissolve
    "She kept doing it faster and faster, and her face was like looking at porn."
    scene laura111 with dissolve
    l "{i}Huff{/i}..."
    scene laura112 with dissolve
    "On top of that, her breathing was heavy and her tongue was out."
    scene laura111 with dissolve
    "She shifted in the sofa as well, if I had to guess, I'd say she was wet herself."
    scene laura112 with dissolve
    "It was still unbelievable, my own mother was jerking me off so invested on it."
    scene laura111 with dissolve
    p "M-mom why are you..."
    scene laura112 with dissolve
    l "Shhh... I already told you, didn't I, baby?"
    scene laura111 with dissolve
    l "I... I may be a bad mom but..."
    scene laura110 with dissolve
    l "I hope I can be a good woman for you..."
    scene laura109 with dissolve
    l "So just sit down and relax as I pamper you..."
    scene laura112 with dissolve
    "She returned to focus solely on my dick, even more resolved than before."
    scene laura111 with dissolve
    "I was puzzled. A bad mom? Not quite, why would she think that?"
    scene laura112 with dissolve
    "But I was in no position to question it, my body was still weak and she wasn't stopping any time soon."
    scene laura111 with dissolve
    "What's more, I could feel my body reaching it's limit. Despite not being able to move, the pleasure was too much."
    scene laura112 with dissolve
    "My hips started to rock up and down to the rhythm my mom was making."
    scene laura111 with dissolve
    l "A-are you close baby? Don't worry, come on, cum as much as possible."
    scene laura112 with dissolve
    l "Come on, I want it too, you are young and healthy, I know you will cover me, won't you?"
    scene laura111 with dissolve
    l "Do it! I want to be covered with your white hot seed! I know it will be delicious, I want to feel it and taste it!"
    scene laura112 with dissolve
    "Was my mom saying all those things to her only son? Well, it was working, I was closer with each word."
    scene laura111 with dissolve
    p "Mom...! I... I will..."
    scene laura112 with dissolve
    l "You are lovely baby... Do it, cum all over your mom!"
    scene laura113 with flash
    l "...!"
    l "T-that's more than I expected! Amazing!"
    "I jizzed all over the place, to my mom and my own surprise, and I didn't stop for a while."
    l "It's throbbing so hard and shooting out more, it's... It's really all over me..."
    scene laura114 with dissolve
    l "... Amazing..."
    l "How was it baby... Are yousatisfied?"
    p "... I... Ah..."
    l "You must be weak still, don't you?"
    l "Don't worry, baby, mom will take care of you... And... Well..."
    l "Judging by this amount of cum, I'm sure you are very healthy, that's one thing less to worry about."
    p "..."
    scene black with fade
    "We laid there for some minutes, I'm not really sure..."
    "She was brushing my forehead with her hand and sometimes traced circles around my chest. Even this was kinda embarrassing."
    "Mom removed all my semen with her other hand and swallowed it, which made my dick harder."
    l "Wow... You surely are eager to go on, aren't you baby? But... Whenever you need to, you can come, you know?"
    "Saying this, mom pulled me aside, since I barely felt my body."
    scene laura115 with dissolve
    l "Hey, [povname]."
    "She walked towards an spot near the sofa, same as last time."
    "She looked a bit doubtful, but certainly more confident than before, she was standing in a very sexy way."
    "Not to mention her chest still had drops of my cum..."
    l "I... I hope you liked it, baby, and take a good look...!"
    l "I may not be so young anymore, and I'm a bit overweighted..."
    p "(Are you kidding me mom? You are stupidly hot... For being my mom, that's it.)"
    p "No mom... I... I think your body is amazing..."
    l "..."
    l "Then... Then... Take a look at this."
    "Clumsily and fast, she started to undo her garterbest, removed her socks and underwear."
    scene laura116 with dissolve
    l "Now I'm completely naked, just like you."
    "Now looking slightly bolder than before, mom started modeling herself for me."
    l "I... I'm a bit ashamed of my pubic hair, but..."
    p "It doesn't bother me, mom, it looks great."
    l "... You are a charmer, aren't you?"
    scene laura117 with dissolve
    l "Then how's this? My ass a bit big, isn't it?"
    p "Mom, I don't know how many times I should repeat myself, your body is smoking hot."
    l "Hehe... Well..."
    scene laura116 with dissolve
    l "It's yours any time you want, baby..."
    l "Just make sure you only do me and only me..."
    p "Mom...?"
    l "Well baby, I should go change and take a shower, your, I'll be right back."
    p "..."
    scene black with fade
    "After that, mom left for a while."
    "I couldn't really move for some time either. But once I did I dressed myself."
    "I had some time to think about all the madness that just happened."
    p "(The woman that gave me life and raised me by herself, she was delighted with my cum.)"
    p "(What do I do now... Should I take her offer? And... Well... Let's not forget.)"
    p "(The reson I'm doing this in the first place is because I needed to check my mom's mind.)"
    p "(For Eileen...)"
    $ renpy.end_replay()
    $ clock.advance_hour()
    scene bg laura_hall with fade
    p "Mom said a lot of off putting things today... I wonder if any of that would shake her enough to go through her mind."
    p "Right now I'm... I need to rest, the day was longer that I thought."
    "That being said, mom was away for quite some time."
    "I could have left at any moment after that, but... I ant to at least say goodbye to her."
    "Imagine going to fuck a woman and then leave without saying a word, let alone if it's your own mother."
    show laura p42_sad with dissolve
    p "Mom...?"
    "Shortly after, she came back only in her underwear."
    "She didn't look that confident, but soon after she tried her best."
    l p12_neutral "Hey baby..."
    p "..."
    l "Ahm... It's getting late, so you should leave, baby."
    l "You can stay if you want, though... But, you must be busy with your university life."
    l "However..."
    l @ p42_sad "If you ever feel horny..."
    l "You can come around any time you want and..."
    l "I may not use clothes again."
    "Mom made a suggestive gesture showing me her nipple for a second."
    p "(I want to say something about everything that have been happening today.)"
    p "(But if I trigger her mind travel, I don't know if I could take it right now.)"
    p "(Or if I can have another opportunity for that matter.)"
    p "(However, I don't want to leave this like this, I know she is not comfortable, so I should say something...)"
    p "Eh... Mom, your... Your hand job was amazing."
    l @ p42_surprised "...!"
    l "T-thanks, [povname]..."
    p "(Yeah, that's not awkward at all.)"
    p "I... You are right mom, I should be leaving."
    l "I will be waiting for you, then, [povname]."
    p "(I actually want to ask so many other things, but, the ambient is a bit awkward.)"
    p "(I'm not even sure if mom's actions or reactions have anything to do with Eileen.)"
    p "(But I do know that her relationship with Miss Julia must mean something.)"
    "Just as I was leaving, I couldn't help but take a last peek at mom..."
    $ laura_first_day_finish = True
    scene black with logodissolve_laura
    jump day_end_laura

label second_day_laura:

    scene black with logodissolve_laura
    $ clock.psychename = ["LAURA"]
    $ clock.hourclock = 0
    show screen clock_marker with dissolve
    scene bg uni with fade
    p "(I'm going to see mom later tonight. I'm still worried about what happened last time.)"
    p "(I need to go inside her mind and find out more and, if not... At the very least set things straight.)"
    p "(This is probably just a misguided way for my mom to try to protect me, so I have to deal with that.)"
    p "(That's why I told her I'm going to her house later today once I'm done with classes.)"
    $ clock.advance_hour(2)
    p "(Or so was the plan. Today of all days we had more work than usual.)"
    p "(I'm a bit later than I thought I would, but that should be ok, or so I hope.)"
    p "(I told mom as soon as I could, so it won't be a surprise for her.)"
    p "(Well, on the bright side, I managed to think better about what I will say.)"
    p "(I'm completely prepared, for the first time in a while, I feel like things won't take me by surprise.)"
    scene bg laura_hall with fade
    p "(I'm nervous. I rang the bell but there was no response. Well now this is a surprise.)"
    p "Where can mom be? She knew I was coming, even if it was late. I came in anyway, but she's not here."
    p "Her keys are in there still, so I don't think she left... Or maybe she did and forgot her keys."
    l "That's very rude, [povname]!"
    p "Mom!?"
    show laura p42_angry with dissolve
    l "I'm just a bit clumsy, not stupid."
    l "Also, stop talking to yourself! I thought you stopped that already."
    p "I... Eh... I'm sorry mom, I was just a bit distracted because-"
    l p32_angry "Because you were late? Well, that's interesting."
    p "Are you... Are you ok mom?"
    p "(Other than the fact that she was in her underwear... Mom almost never acts like this.)"
    l "I..."
    l p12_sad "I was worried about you, you know?"
    l "I'm sorry, I didn't meant to yell at you or be mad at you, I just thought..."
    l p12_neutral "Nevermind, baby, I'm happy you are finally home. I had food prepared, but..."
    l "It's cold by now."
    l "Besides... Why eat that when... When..."
    l p32_neutral "When you can eat me."
    p "Mom... Have you been watching anime again?"
    l p32_surprised "...!"
    p "{i}sigh{/i}... Listen, I know you have not a lot to do, but watching anime is not that productive."
    p "(But it explains where she got these weird ideas from, I think.)"
    l p22_sad "So... We are not going to do anything today?"
    p "Mom, I think we have some things to talk about before that."
    l p22_happy "So we are actually going to to do it later!?"
    p "Mom, please stop and think, you think this is correct?"
    l p42_sad "Hm...?"
    p "Mom, this is a big misunderstanding, and things are not like they are in anime."
    l p42_serious "Misunderstanding? Well... Let me ask you a question."
    l "Are you doing it with Miss Julia?"
    p "Wait, mom, it's not-"
    l "Yes or no?"
    p "... Yes, I am."
    l "There's no misunderstanding, then, is it?"
    p "...!"
    p "(Mom is surprisingly sharp... She shattered anything I was about to say just with that.)"
    p "(What's more, she doesn't met me explain myself.)"
    l "..."
    p "Mom, if only you'd let me explain, it's not-"
    l p43_serious "..." with dissolve
    l "Let's do it, [povname]."
    p "Mom, wait a minute."
    "Mom was trying to undress, massaging my dick and rubbing herself against me."
    "She was kind of desperate while she was doing it. This has to stop."
    p "Mom...!"
    l "Come on, [povname], I want it too!"
    p "Mom... Just...! Just...!"
    p "CAN YOU LISTEN FOR A SECOND!?"
    l p33_surprised "...!"
    p "Mom, it isn't what you think, calm down for a moment!"
    l p13_sad "A-alright..."
    p "Listen mom, the truth is, yes, I was having sex with Miss Julia, but it's not what you think."
    p "I have no idea what she told you about us, but it's... It's embarrassing to say, but I've been basically forced to do so."
    l p13_surprised "...!"
    p "I've had other reasons to be around her, alright, and it isn't sex."
    l p13_serious "Then, why? What is it?"
    p "I'm looking for someone who is missing, ok?"
    l p13_surprised "S-someone's missing!? Who!?"
    p "It doesn't matter... I... It's complicated."
    l p13_sad "Come on, baby, I want to help if possible..."
    p "It's alright mom. Listen, is complicated, but you won't even remember her."
    l p13_serious "Try me."
    p "... Alright. Look, it's Eileen, ok. Eileen is missing. Eileen Be-"
    l p13_surprised "Eileen is missing!?" with flash
    p "(Of all things this is it!?)"
    p "(Wait...)"
    p "(Mom remembers Eileen!?)"
    p "(N-no time to waste, I have to go in...!)"
    "And as in the previous times, I made the gestures and..."
    p "Here I go, mom...!"
    scene black with pixellate
    $ inpsyche = True
    $ clock.hourclock = 0
    scene bg white town with pixellate
    p "..."
    p "Man... I forgot how creepy this site is, and there's that figure I saw last time."
    p "I should be careful, now I can't leave as I did before..."
    p "Also, mom is right, I should stop talking to myself."
    p "..."
    p "The silence of this place is also very unsettling. I guess that's another reason why I keep talking."
    p "Worst case scenario, whatever is out there will spot me because of this..."
    scene black with fade
    "I walked this god forsaken place for some time."
    $ clock.advance_hour(2)
    scene bg white town with pixellate
    "I thought I was crazy, it was so amazingly quiet it was almost as if there was no sound in this world."
    "I caught myself talking to myself several times just to confirm I wasn't deaf."
    "I also realized this world is all the same, it's the same block of apartments over and over."
    "This was completely surreal, if it wasn't for my clock, I couldn't even tell the time, everything is just..."
    "It's gray and dead. Is this really mom's mind? At this point I'd be grateful just to see that thing I saw last time."
    $ clock.advance_hour()
    "I've been walking more than half a day at this point, and even if I'm not tired, I'm mentally exhausted."
    "That alone seems to take a toll on me on this world..."
    unk2 "I told you! Get off there! He's gonna come here any time soon!"
    "Just when I was about to give up, I heard an strange voice out of nowhere."
    p "People...?"
    unk "Relax, he probably lost all hope now and he is about to plunge to despair, not like it matters."
    "I decided to lean a bit closer, and it was quite the view."
    scene lauraextra201 with fade
    unk2 "But what the actual hell are you doing!?"
    unk "You said hell."
    unk2 "You... You... Why are you doing this!?"
    unk "Much better, princess. I need to go out once in a while, you know."
    unk2 "We both know what happens whenever you do that. Please, please return!"
    unk "No."
    unk2 "...! You...! You...!"
    "I was lost for words, there was an angel and a devil. I started considering that I died."
    "Whether this is heaven or hell, it's very empty."
    scene lauraextra202 with dissolve
    unk "Calm down, big baby, nothing wrong is going to happen, if something, you are making way too much noise."
    unk2 "...! I... You... {i}sigh{/i}... Just get this over with..."
    unk "Relax, besides, tell me you are not enjoying the show."
    unk2 "... I'm not! We basically have the same body."
    unk "Maybe, but I dress better and I know how to move."
    unk "Hell, we have the same boob size and mine still look bigger."
    unk2 "I don't care about that!"
    unk "If you were a guy you'd have a boner."
    unk "...!" with flash
    unk "H-hey, I hope you enjoyed the show."
    unk2 "I told you, I'm not interested in that!"
    unk "Well, that's a shame, you should have, we are done for, after all."
    unk2 "What do you...?"
    scene lauraextra203 with dissolve
    "In the mid of her... Pole dancing...? Routine the devil had, she pointed right at me with her legs."
    unk2 "...!" with flash
    unk2 "No... No... We gotta.. We gotta..."
    unk "You are right, we gotta..."
    scene lauraextra204 with dissolve
    unk "We gotta introduce ourselves properly!"
    p "What the!?"
    "In the blink of an eye, the devil was right in front of me much to the angel's disbelief."
    de "Hi! My name is Asma, it's short for-"
    unk2 "ASMA! STOP RIGHT THIS INSTANT! YOU CAN'T-"
    de "Hush it, self-righteous bitch. I have to take this opportunity."
    de "We fucked up already so we might as well push our knee deeper."
    de "Ignore her, she is an stick in the mud, the kind of person you'd take advantage of back in highschool."
    p "Alright...?"
    de "So, what's your name, cutie?"
    p "... Ah... My name is [povname]."
    de "[povname], huh? Nice to meet you! You look like a healthy young guy, you know?"
    de "I know we just met, but I was thinking if you could-"
    scene lauraextra205 with hpunch
    unk2 "Stop it!"
    de "HEY!!!"
    unk2 "Listen, [povname], this place is not safe, you shouldn't be here in the first place."
    p "I have things to do here!"
    p "(I just don't know what exactly what right now.)"
    de "COME ON RAQ! WE HAVEN'T HAD A FRIEND IN A LONG TIME!"
    unk2 "I don't care what is your business here, you should leave!"
    p "What!? But... I'm here looking for my mom."
    unk2 "Mom...?"
    de "HEY YOU BITCH GET OFF ME!"
    unk2 "Wait, who is your mom?"
    de "GAAAAAAH!"
    unk2 "...!"
    scene lauraextra206 with hpunch
    de "Don't you even know what a mom is!?"
    de "You are fucking heavy, I could have died."
    unk2 "You are immortal, dummy, you are too mean to die!"
    de "Yes I am bitch, you are about to see how mean I can be!"
    p "Ladies?"
    unk2 "Last time you tried you know how it ended!"
    p "Ladies...?"
    de "That was just luck, want to try it again!?"
    p "LADIES!"
    p "This isn't working... First couple of persons I know and they are beyond crazy."
    p "I should leave, I still have some hours before-"
    unk "ENOUGH!" with hpunch
    scene lauraextra207 with dissolve
    de "...!"
    unk2 "...!"
    p "...!"
    unk2 "L-look what you did! She is coming now!"
    de "Me!? If you weren't so loud I would have-"
    unk "SHUT! UP!"
    de "Y-yes!"
    "The air kinda froze when whatever came talked."
    "The whole place that was completely dead, other than the cries of the two in front of me, is now kinda trembling."
    "And as that thing came closer, things got a worse."
    scene lauraextra208 with dissolve
    l "WHAT ARE YOU DOING HERE. WHAT DID I TOLD YOU TO DO!?"
    l "GUARD THE GODDAMN PLACE! AND HERE YOU ARE DOING THE CONTRARY OF THAT."
    l "AND NOW YOU FUCKED UP!"
    "Is this really my mother...? It's hard to tell..."
    "Now that I think about it, they kinda look similar?"
    unk2 "This dummy didn't want to do her job, she roped me into this."
    de "I was just having fun, you couldn't stop making ruckus, that's why-"
    l "YOU BOTH FAILED!"
    scene lauraextra209 with dissolve
    l "What's more, look what you've done. I gave you simple instructions, and yet here we are."
    "They both looked regretful of what they have done, both in their own ways."
    l "You. I told you last time, you shouldn't be here."
    "This time she talked a lot more calmly. She is intimidating."
    p "I... Sorry, mom, I'm here because I'm looking for an information. In fact, I was looking for you."
    unk2 "Mom...?"
    l "I know, and there's nothing here for you. You shouldn't be here, [povname]."
    p "(Huh!? She knows my name!?)"
    l "I have an idea why you are here, but I don't know anything."
    l "Leave this place immediatly."
    p "W-wait! It's about-"
    l "About Eileen. Eileen Becker. I remember her. You know I was never against your friendship."
    l "But seeing the circumstances, I think you are better off not finding her."
    p "...! HOW CAN YOU SAY THAT!?"
    l "You must think I'm being hesrtless, [povname], but trust me, this is for your own good."
    p "You may look like my mother, but you are nothing like her!"
    p "You must be some kind of twisted reflection of some part of her."
    l "You know nothing about your mother."
    p "..."
    l "I'll take my leave. Alma, Raquel, I hope you will take care of this on your own, won't you?"
    an "Y-yes, ma'am..."
    de "Yeah..."
    l "Good. And listen to me, [povname], if you ever come back..."
    p "..."
    l "Hope that's something you understand."
    p "(If she is threatening me, it isn't the first time in someone's mind...)"
    scene black with fade
    "She left just like that, almost at speed light, but there wasn't even a bit of wind on her trail..."
    "There I was left with the devil girl and the angel, both looked somewhat in distraught."
    scene bg white town with pixellate
    show angel pp11_sad at charaleft with dissolve
    show devil pp21_serious at chararight with dissolve
    de "..."
    an "..."
    an "S-so... What are we going to do now?"
    de "You heard the boss, we need to get rid of him somehow."
    p "W-what do that even means?"
    an "Hey... [povname], can you please leave?"
    p "Listen, even if I wanted to, I can't."
    an @ pp11_neutral "... What you are doing here? it must be very important for you, then."
    an "But... It's a problem for us..."
    de pp11_angry "Stop hitting around the bushed, the man already said he can't leave."
    de pp11_sad "Listen, cutie, we can't do a lot about this now..."
    p "W-what are you gonna do?"
    de pp21_neutral "That's a good question."
    an @ pp21_surprised "You don't know!? That was supposed to be your job!"
    de "Well, I'm not very reliable."
    an "..."
    de "Well, cutie, any idea."
    p "... I'm sorry, I'm lost. W-What are you supposed to do anyway?"
    an "W-well..."
    an pp11_neutral "This dummy over here was supposed to get rid of any intruder they found."
    p "H-how...? Are you supposed to kill me?"
    de "Maybe. I'm not really sure. If I'm honest, I overslept that part."
    p "..."
    an "..."
    an pp21_surprised "W-what do we do now!?"
    de pp11_neutral "Hmmm... Relax, I'm sure it will be alright!"
    an pp21_angry "No it will not! You know well what will happen if this thing is here at the time she is back!"
    p "Thing?"
    de "Well, I don't have any ideas, really, so even if I wanted, there's nothing we can't do."
    an "YOU'LL MAKE ME GO CRAZY ONE OF THESE DAYS!"
    de "Honey, I think you already are."
    an "You...! YOU...!"
    p "H-hey, calm down. If it helps at all, I will be leaving at the end of the day."
    an pp21_happy "Really!? We are saved!"
    de @ pp11_serious "I'm sorry honey, but we still have a long way till the day ends."
    an pp21_surprised "...!"
    de "So yeah, nothing solved yet."
    an pp11_sad "You love crushing my hopes and dreams, don't you..."
    p "Eh... What if you hide me until I leave?"
    de "See? This guy gets it. He is a person with initiative, vision..."
    an "And problems with us."
    p "Listen, I'll cooperate, alright? I wouldn't like to cause you troubles. And I'd like to remain alive as well."
    an "{i}sigh{/i}... Nothing that we can do now..."
    an pp11_neutral "Please if you have any ideas of what can we do..."
    p "As I said, I can just hide. Don't you guys have a place where we could go to?"
    de @ pp21_happy "As I matter of fact, yes!"
    de "You see, whenever I need to slack off, I realized that the boss has control all over the place."
    de "EXCEPT! In the building rooftops."
    an pp11_sad "You slack off...?"
    de "Of course, like any natural person would under these conditions. Enjoy your life a bit."
    de "So let's go quickly!"
    an pp21_surprised "R-right!"
    hide angel with dissolve
    hide devil with dissolve
    p "..."
    p "..."
    show angel pp11_serious at charaleft with dissolve
    show devil pp21_serious at chararight with dissolve
    de "What's the matter, cutie?"
    de pp21_neutral "You wanted to see us leave, don't you?"
    de "Stop it, you pervert, we need to leave already."
    p "Eh... I don't know if you realized, but I don't have wings, or any means or flying."
    de pp21_sad " Man, you are very useless, aren't you?"
    de pp11_happy "Oh well, I guess we have to lift you now."
    de "Hey, you, come here and give me a hand."
    an @ pp21_surprised "A-alright!"
    scene black with fade
    "Without effort, they took me by the shoulders and flew me to a nearby rooftop."
    scene bg white roof with fade
    "The scenery was as I expected, buildings everywhere, and the rest is white and dead."
    p "This place is very... Peculiar."
    show angel pp11_serious at charaleft with dissolve
    show devil pp21_neutral at chararight with dissolve
    de "Regardless, it seems like we dodged one."
    an "What do you mean with a peculiar place?"
    p "I don't know how to put it... This place is inert."
    an "\"Inert\"? What does that mean?"
    de @ pp11_neutral "It means that it feels like a shithole, idiot."
    an @ pp11_sad "Oh..."
    p "I... I mean, why is this place like that?"
    an "What do you mean?"
    de "Well, cutie, this is honestly normal for us."
    p "But is there a reason? I get the idea that these places are the way they are for a reason."
    de pp11_serious "These places?"
    p "(I see, she seemed like she knew more, but it seems like she doesn't know this is a psyche.)"
    p "Nevermind that... What about your boss?"
    de "Our boss?"
    an "The lord?"
    p "\"Lord\"...? Eh... Yeah, the lady that came before."
    de "Well, she created us."
    an pp11_happy "Yeah, that's why she is our Lord."
    an "She is the most capable, strong and perfect being. We can't compare, and so we have to serve."
    de pp11_neutral "You heard the fanatic. Truth is, yeah, boss is pretty amazing."
    p "... If she is so amazing, why can't she \"see\" us here?"
    an pp21_angry "HOW DARE YOU!?"
    an "First of all, we don't even know if this babbler is right about that!"
    de "Hey, trust me. I've been slacking off for a long time here, you know."
    an "And doing what exactly!?"
    de "I masturbate in the corner of the building."
    an pp21_surprised "You... What...?"
    an pp11_serious "Nevermind..."
    p "But how is she planning on getting to us, then?"
    de "I suspect she somehow monitors anything that happens in the ground. She'd know where you are all the time."
    de "But in the rooftops is different."
    p "Why?"
    de "I guess she doesn't expect anyone to get here. You can't fly, can you? Why would an intruder be different?"
    an "... Actually, it can happen."
    p "Hm...?" with flash
    de "Nah, besides, I don't have any more ideas where to hide cutie over here."
    an pp11_sad "I guess you are right..."
    an pp11_serious "Where do you come from, [povname]?"
    p "It's... Complicated."
    an "Do you...?"
    an pp11_surprised "Do you come from the same world our Lord does?"
    p "Eh... Yeah, that's kind of it."
    an "..."
    an pp11_angry "That can't be! You are not half as cool! You can't even fly!"
    p "Well, we come from the same place, but we are not the same...?"
    an pp11_surprised "Right. It makes sense."
label laura_scene2:
    if _in_replay:
        scene bg white roof with fade
        show angel pp11_serious at charaleft with dissolve
        show devil pp21_neutral at chararight with dissolve
    an pp21_surprised "OH RIGHT! ABOUT THAT!"
    p "...!"
    p "(This woman is very unestable!)"
    scene laura201 with dissolve
    an "You called our lord a mom, what is that?"
    de "Not again... You missed the bees and the flowers, didn't you?"
    de "You see, when a hung guy loves the hot chick very very much they-"
    scene laura202 with dissolve
    an "I know how it works! Don't talk to me like a child!"
    de "Then stop acting like an idiot!"
    an "I was just wondering! Seems like this thing is related to our lord in some way!"
    de "Well you..."
    scene laura201 with dissolve
    de "You are actually right. Cutie right here seems to be related somehow to our boss."
    de "You already said you are her kid, right? Are you? Not like us but like bees and flowers?"
    p "(That's an interesting way to put it.)"
    p "Well, first of all, who even are you?"
    an "My name is Raquel, the angel."
    de "And my name is Alma, the devil. Very very pleased to meet you, handsome."
    p "Yeah, I heard mom saying your names before. But, WHAT are you?"
    de "We already said it, dummy, I'm a devil, she is an angel. Maybe pay more attention."
    p "N-no, that I get, it's just-"
    de "Or maybe you can't focus, I'm guessing all your blood is rushing to-"
    scene laura202 with dissolve
    an "Alma, stop!"
    de "What? I was going to say his face, look, he is blushing."
    p "..."
    an "This is serious!"
    scene laura201 with dissolve
    an "P-please forgive her. She is being extra annoying now for some reason."
    de "Can't deny that, I feel like I'm in matting season!"
    an "P-please ignore her."
    de "If you can."
    p "R-right... I meant, what are you in relation to my mom. How are you both related to her."
    an "We are... We are not sure."
    de "It's complicated, we just are, I think."
    an "..."
    de "But you know... We can try the bees and flowers thing."
    an "... Huh...?"
    de "You certainly need a lesson on this, and since it's usually just the two of us..."
    de "Although, we can also do it if you want, but-"
    scene laura202 with dissolve
    an "Absolutely not!"
    de "Come on, don't be like that, self righteous bitch."
    de "Besides, I will do it you want me or not."
    an "W-what are you-"
    scene laura203 with dissolve
    an "Waaaah! Not again!"
    de "So, wanna do it, cutie? I've never seen a dick, but I know everything about them!"
    p "I... Don't think it's a good idea right now."
    an "Listen to him! You can't! What if he's just like our lord?"
    de "He already said he isn't! And even if he was, that only makes me hornier!"
    an "What!? Wait!"
    scene laura204 with dissolve
    "Pushing the angel away, the devil exposed her big breasts right in front of me."
    de "So? What is it, cutie? Wanna do it? Huh?"
    p "I don't think it's a good idea, what about your boss? What if she comes?"
    de "Well, I wouldn't be worried about it, even if she does something wrong to me..."
    de "Truth is, I'd die happy as long as I can experience a cock."
    de "And look at your pants! You are getting bigger, aren't you?"
    de "Look! Look! My pussy is wet too!"
    "True enough, even if I didn't realize, her pussy was exposed, it was the same color as her skin."
    p "R-right... But I am worried about what may happen to me, and, well, to you."
    de "Awwww, how charming, but I'm not interested in any white knight right now."
    "There doesn't seem to be any way to turn her down right now. To be honest, it is true I'm hard."
    "I find the color of her nipples strangely hot as well."
    p "Alright. But, eh... We are exposed here, so let's do this qu-"
    scene laura205 with flash
    p "...ick? What the fuck?"
    de "No turning back now! And my God! It's huge! Well, that or maybe this is just the first one I've ever seen in person."
    p "Rude."
    de "Get used to it, honey. I will get really rough soon enough."
    "Gee, she even throw away her own clothes. Where are they!?"
    an "...!"
    "As we were talking with my dick out, the angel was looking at us in shock."
    de "Let her be, sweetie, better that way, this cock will be completely for me! Isn't that right?"
    p "... Just hurry up, who knows when mom will show up."
    de "Party pooper, let's enjoy this, so don't worry about that."
    an "W-wait! He is right!"
    de "Shut up, pansy."
    an "Don't call me that! I'm not a flower! Although, flowers are pretty..."
    an "Wait!"
    scene laura206 with dissolve
    de "Hoho, look who decided to be a cool girl."
    an "It's not that, it's just... I... Ahm..."
    de "... Hehe."
    an "..."
    de "Look at you, a little bit more and you are going to start drooling."
    de "So much for being perfect. I think you are slowly taking my place now!"
    an "I-it's not that!"
    de "At least look at me when you say that, can you?"
    an "Uh... It's just... It's so scary, what if I look at you and it attacks me?"
    de "Nah, you are safe, trust me, isn't that right, handsome?"
    p "sigh... It won't hurt you."
    an "It's so big, though..."
    de "Right! Isn't it? Now you are getting into this!"
    "I felt blood rushing to my face and my face becoming hotter. I had no doubt I was blushing."
    p "L-listen, Raquel is your name, right?"
    an "R-right! That's my name, sir!"
    "She shocked once I said her name, for some reason. What with the sir?"
    p "You don't want to be caught by your boss, right?"
    an "Y-yes!"
    de "Insufferable, but I like where this is going."
    p "Well, I need your help, too, so we can finish this quickly before mom can find out."
    de "Yes, definitively like where this is going."
    an "H-how can I help?"
    de "Well, of course she wouldn't know, it would be easier and faster for me to show her."
    scene laura207 with dissolve
    de "Here."
    p "Ung...! W-wait!"
    "Just like that, Alma, the devil, was at my dick rubbing her tits up and down."
    an "...! A-are you ok!?"
    de "Relax, goody two shoes, he is loving it, isn't that right?"
    p "Y-yeah... She is right."
    p "(Although I was thinking more along the lines of a blowjob, even a damn handjob.)"
    p "(She jumped right to the boobjob, though.)"
    an "And you, Alma? Are you ok? How does it feel."
    de "Let me describe it first."
    "The devil said playfully while glancing at me, then looking at the angel again."
    p "..."
    de "The thing between my tits right now needs some massaging."
    de "It feels veeeeery hard and hot. Every time I move my tits up and down, it throbs."
    an "I-I see..."
    de "It may look menacing, but truth is, you need to be delicated."
    de "My tits are big and soft, and yet firm enough to envelop it's whole girth."
    p "..."
    de "Even if I tried, I can't possibly envelop it completely."
    de "But that's ok, every time I feel this big, hot thing throbbing between my tits..."
    de "Truth it I like it very very much, I can feel my own heart throbbing as much."
    de "My own body gets very very hot. And I feel a tingling sensation between my legs."
    p "(Jesus, she is stupidly good with this dirty talk.)"
    de "The tingling sensation doesn't stop there, my insides are getting moist, you know why?"
    an "W-why...?"
    de "Because this huge thing isn't supposed to just be between my tits."
    de "This is supposed to go inside me, it's supposed to stir me up completely, it would likely almost split me in half."
    de "But you know what, considering how good this feel between my tits, I'm sure I'd lose my mind as soon as it is inside me."
    p "...!"
    p "(F-fuck...! She is moving ever so slowly, but listening to that pushed me to the fucking edge.)"
    de "Isn't that right, handsome...? You've been awfully quiet there."
    p "..."
    "I couldn't do a single thing more than nodding. Is this thing before me really a virgin...?"
    "All the while the devil was looking at me with a very mischivous smile. She knows what is going on."
    "She wasn't the only one. The angel didn't know where to look at, my dick between her partner's tits, or me."
    an "..."
    "After looking at me, she ultimately said with a very shy, almost shivering voice."
    an "Mmm... M-me too..."
    de "What was it? I couldn't quite hear."
    an "I want to... Do that to..."
    de "Speak a bit higher, darling, I think having this huge, hard and hot cock between my tits is a bit distracting."
    an "I want to do it too...! Please."
    de "Awww, alright, a bit too weak still, but I think you will get your prize."
    de "And so will I!"
    p "Wait, what are you-"
    scene laura208 with dissolve
    de "Hush, cockboy, and put your mouth to good use!"
    p "Hm! Hm!"
    de "Good boy, now let me take care of everything!"
    an "Ahm... What should I..."
    de "For now you can begin by letting your tits out. They look massive, I wonder if they are bigger than mine."
    an "I-I think we are about the same size."
    de "And yet yours look bigger somehow, you cheater."
    de "Doesn't matter, though, I'm the one being eaten out and..."
    de "Hah..."
    de "He is not half bad at it."
    an "E-eaten out!?"
    de "Relax, it's a matter of speech, he is doing a great job, and let me tell you a secret..."
    de "It... It feels fantastic! Hah...!"
    de "Or you would know if you stopped staring at his dick."
    an "I think it's still a bit scary."
    de "Nevermind that, I'll be having my fun, just watch."
    an "... What is he doing?"
    de "Well, let me ask you a question, while watching this, how are you feeling?"
    an "... Hot..."
    de "You'll have to talk louder if you want me to... Hah... Keep paying attention."
    an "It makes me feel hot..."
    de "And where are you hot the most?"
    an "In my face... In my breasts, and... And..."
    de "And... Hah... I don't have all day, or all sanity, for that matter."
    an "Between my legs, it feel really hot... It's wet."
    de "Well, guess what is he doing to me, he is using his tongue all over that place for me and me alone."
    "True enough, I did't have any option, I was trying my best to make her come and put an end to this."
    "Alas, a futile attempt. I'm having a hard time believing she is a virgin."
    an "..."
    de "Haha! I can tell how turned on you are, your nipples could cut rocks!"
    de "H-hey, I have an idea!"
    p "Hm...?"
    de "You don't want to touch his dick, but I bet you want to experience this."
    de "This is kind of an awkward position, for him at least, so here, help me out."
    p "..."
    an "W-what should I do?"
    de "Hey, handsome, I didn't say you could stop but... Raquel, go behind him and pull him up, now!"
    an "R-roger!"
    p "Hm!?"
    scene laura209 with dissolve
    de "Ata, boy!"
    "In an instant, true to her word, the angel was holding me from behind while the devil had me by the legs."
    p "W-what the fuck, be careful, I may fall down!"
    de "I wouldn't date letting go such a nice cock, honey."
    de "And boy am I in a great position to just suck you off completely."
    de "But alas, I have a better idea."
    de "Raquel, let's lift him up."
    p "What!? How is that a fucking better idea!?"
    an "I-I agree with him, what if he falls...?"
    de "He won't. If you do what you are told. You saw how I was before, right?"
    an "R-right..."
    de "Do the same but lock your legs with his arms. I'll hold his leg, and that way he won't be able to fall."
    de "Trust me, it will be an experience, to all of us as well."
    p "W-wait!"
    an "R-roger!"
    scene laura210 with dissolve
    "And in a second, we were basically having flying sex."
    an "Ah... It feels... Nice..."
    de "He have not even began yet! Just wait for it. In the meantime, let me give your cock a nice tit massage."
    p "..."
    de "Hey, better do something, otherwise we can just leave you fall..."
    an "I... Hah... Hah... I would... Would never... Hah..."
    de "Take a hold of yourself, I can't even imagine what your reaction will be once you begin."
    an "I... The top of his mouth... Against... Against my vagina..."
    de "Yeah yeah, basically. So how it will be, handsome, honestly, you have nothing to lose."
    "I was thinking to myself that it would be pointless. The angel is shivering, I'm sure she will cum in any minute."
    "But that would be ultimately pointless, I doubt she or the devil will stop any time soon..."
    "So I might as well indulge, at this point."
    an "..."
    "As I said, she started shivering even more, I couldn't really look around, though."
    de "Oh...! Did he start already? Your face is a poem..."
    an "..."
    de "Hey, say something. What is i-"
    an "Aaaaaaaaaah..."
    p "...!"
    "She grabbed my hair and pulled me harder against her pussy. I didn't have too much room to breath that way."
    "However, she was shaking extremely hard. Every time she did I could breath a bit."
    "Basically, if I don't want to die suffocated, I need to eat her up as if my life depended on it. Which probably does."
    de "H-holy shit...! Haha... I wasn't expecting you to go this wild...!"
    an "Ah... Hah...! Hah...! More...! Harder... It feels good...!"
    de "Oh well, with that taken care of, I will keep enjoying this big throbbing cock as if there was no tomorrow!"
    de "Because if boss comes around, that may as well be the case!"
    "That did worry me a bit. The angel was too self-absorted into it to even think of anything else."
    "And true enough, my god, her tit job is really getting to me. She is being very rough with me."
    "These two women... They may really end up killing me, either by falling, by exhausting me, or by getting myself caught with mom."
    "But even then, I can't deny I'm in heaven. The sensation is fantastic, and I'm literally flying with two attractive... Eh... Girls...?"
    de "Gee... I can't take it anymore, handsome, I think it's time for-"
    l "For what?"
    an "...!"
    scene laura211 with dissolve
    de "B-boss... W-what are you..."
    an "Oh no... Oh no... I knew this was a bad idea..."
    de "H-how... When... Since when..."
    l "I've always knew where your lazy ass is whenever you want to slack off."
    l "I don't particularly mind, but you know why I don't? It's because I expect you to do your job regardless."
    l "But here we are, aren't we."
    de "S-sir, you see, it's just-"
    l "And you, Raquel, I'm just disappointed."
    an "I know..."
    an "Well, fear not, children. Your punishment is..."
    an "Death."
    scene laura212 with flash
    de "W-wait, you can't be serious...! L-let me explain! This is just an-"
    l "No excuses."
    an "P-please, forgive me... I tried to stop it, but-"
    l "But you didn't. You were enjoying yourself as much as Alma was."
    an "... Please..."
    l "More importantly, looks like you both dropped something."
    an "... Ah! Oh no!"
    de "Oh shit! Oh shit! Oh shit! No!"
    "Indeed, as they were talking, I was plummeting down to my death."
    scene laura213 with flash
    "I saw a bright like as I was falling down. I could see the silhouettes of the idiots who let me fall."
    "But I also saw a shadow, it was a matter of seconds. Mostly because I started rolling as I fell."
    de "Well, there she goes."
    an "At least he will be ok..."
    scene black with hpunch
    "I'm guessing this is it. This is how I die."
    "THUD" with hpunch
    p "What the...!"
    l "Open your eyes."
    scene laura214 with dissolve
    de "Hi, cutie."
    l "Don't call him that."
    de "..."
    p "... Am I not dead...?"
    l "No."
    p "Are you going to kill me?"
    l "No."
    p "Then what-"
    l "Stop asking pointless questions. Whether you know the reason or not is irrelevant."
    l "And don't talk if it's not neccesary. The least you get to know, the better."
    l "Why are you even still here, you should have left already."
    p "I can't..."
    l "Of course you can. You are just an stubborn child. And I have to teach you a lesson."
    an "W-what are you gonna do with him?"
    p "(That's a good question.)"
    l "I can't let this go to waste, can I...?"
    scene laura215 with dissolve
    de "B-boss... Are you seriously going to...?"
    "She pulled her dress up and "
    an "What we were doing before...? You are supposed to be on his face."
    l "What I said before apply to you two as well. Don't you dare talk unless I directly ask you."
    de "R-roger...!"
    an "S-sorry..."
    l "Now, I'm going to fuck you, and I'm going to fuck you good."
    an "W-wait, mom! Don't-"
    scene laura216 with dissolve
    l "Don't call me that."
    p "Guh...!"
    "Mom lowered herself on me without a second thought."
    "Even though I was only half way there, her pussy filled me with an overwhelming pleasure."
    de "Hoho...! Look at that...!"
    l "What did I... sigh... Nevermind, Alma."
    de "Look, look, the tip is in, how does it feel, boss?"
    l "I'm not here to make commentary, Alma, this is a lesson."
    de "But I want to see!"
    l "If you keep going you'll have to leave."
    de "A-alright, I'll keep it down. As much as I can."
    an "Does it hurt?"
    l "For me or for him? Not like it matter a lot. Please, dear, stay back and observe."
    scene laura217 with dissolve
    p "H-huh...! W-what the..."
    l "Mouth shut. You are not allowed to talk, just keep it in your mind. Amazing, isn't it?"
    p "Hah... Hah...!"
    de "He doesn't need to say anything, he is breathing very heavily!"
    an "He looks like he is in pain."
    l "He is not. And just like with Alma, keep pushing these trivial things and you'll be out."
    an "..."
    l "My pussy should be feeling like nothing you've ever felt before, isn't it?"
    p "Hah...!"
    "She was not even movie and the pleasure was maddening. What would happen if she even starts moving!?"
    "It felt as if every part of her pussy was trying to milk me. And the sensation rushed all over my body."
    p "H-how...!?"
    l "No talking, and stop asking pointless questions. If you don't want to leave, I'll force you to."
    scene laura216 with dissolve
    p "W-woah...!"
    "As soon as she pulled off of me, I immediately shock."
    l "You should have left when you had the chance."
    scene laura217 with dissolve
    p "Gah...!"
    "Again, an explosion of sensations exploded and filled my whole body."
    de "No wonder you are the boss! Amazing! He shivering and all!"
    de "Isn't he supposed to cum, though?"
    l "When I see it fit."
    "Despite all the stimulation, I didn't felt like cumming."
    p "(W-what is even going on!?)"
    l "Don't worry, this should be over soon enough."
    p "Hah... Hah..."
    scene laura216 with dissolve
    l "I wonder if you are even enjoying this, must be reallt desperating."
    scene laura217 with dissolve
    l "I can tell you want to cum, but I won't let you."
    scene laura216 with dissolve
    de "He is making all kind of faces."
    scene laura217 with dissolve
    an "He also looks in pain..."
    scene laura216 with dissolve
    l "I don't think he is in pain per se."
    scene laura217 with dissolve
    l "He seems to be losing his mind over the pleasure, though. Good."
    scene laura216 with dissolve
    p "HAh! Hah!"
    scene laura217 with dissolve
    an "I must admit... The sounds he is making are kinda cute."
    scene laura216 with dissolve
    de "They are fucking hot, I want to do it too."
    scene laura217 with dissolve
    l "No. Also, take this as a warning."
    scene laura218 with dissolve
    p "H-huh...?"
    scene laura219 with dissolve
    de "Boss, why are you stopping?"
    l "Look at his face. This is an step further."
    p "Hah...!"
    "Yes, when she pulled off of me it was an actual relief. Her pussy is unbelievable."
    scene laura218 with dissolve
    p "Guh...! Hah...!"
    de "Wow, that's so cool."
    an "..."
    "This woman is attacking me relentlessly, and even with all this pleasure, I can't cum."
    scene laura219 with dissolve
    p "Hah...! S-stop...!"
    l "I can't. This is for your own good."
    "Is this woman... Is this woman truly my mother."
    scene laura218 with dissolve
    l "Well, you had a taste of it already, so... I'll let you make a single choice."
    scene laura219 with dissolve
    p "Hah...!"
    scene laura218 with dissolve
    l "But trust me, it won't really matter."
    scene laura219 with dissolve
    l "So, do you want to cum in or out?"
    scene laura218 with dissolve
    "It... It doesn't matter...? Then... Then why...?"
    scene laura219 with dissolve
    l "Hurry up, or I won't let you cum."
    menu:
        "Where should I cum?"
        "In":
            scene laura218 with dissolve
            l "So you want to cum in. Alright."
            scene laura219 with dissolve
            p "W-wait, how...!"
            scene laura218 with dissolve
            l "Do it, now."
            scene laura219 with dissolve
            p "W-wait... How... I..."
            scene laura218 with dissolve
            l "Just do it as normal."
            scene laura219 with dissolve
            p " Hah...! Cumming...!"
            scene laura222 with flash
            l "Haaah..."
            p "Hah...! Hah...!"
            de "Hoho! You are taking it all in boss! And even then some is leaking out!"
            de "It looks amazing, I want to feel it too...!"
            an "He is moving desperately, is he ok?"
            de "Hehe, I assure you he totally is, look at all that jizz!"
            l "Cum until the very last drop of cum."
            "Wave after wave of pleasure was assaulting me while inside her pussy."
            "I couldn't stop cumming and even as I was her pussy was still milking me every time."
            scene laura223 with dissolve
            l "Even given the circumstances, that's quite a big amount of cum."
            de "Wow boss, your face there was-"
            l "..."
            de "B-bad topic. But look at your pussy, even though he came inside, it's everywhere, and it's ever slightly leaking out of your pussy still."
            p "Hah... Hah..."
            l "That's because he hasn't stop cumming."
            de "Amazing, I really want to-"
            l "You won't."
            de "R-right...! H-hehe...!"
            an "M-me too..."
            de "Tough luck, dummy, seems like the best we can do is watch."
            p "Hah... Hah... N-now... W-what...?"
            l "You are still not allowed to talk. And seems like this isn't over."
            p "W-what...?"
            l "You are truly amazing. Let's continue."

        "Out":
            scene laura218 with dissolve
            l "So you want to cum outside. Alright."
            scene laura219 with dissolve
            p "W-wait, how...!"
            scene laura218 with dissolve
            l "Do it, now."
            scene laura219 with dissolve
            p "W-wait... How... I..."
            scene laura218 with dissolve
            l "You'll cum as soon as I oull off."
            scene laura219 with dissolve
            p " Hah...! Cumming...!"
            scene laura220 with flash
            l "There you go."
            p "Hah...! Hah...!"
            de "Hoho! It's flying all over, and it's so much and so thick, amazing!"
            de "I-it's going to cover you all, boss!"
            an "He keeps moving his hips, it's making all the white... Goo land all over."
            de "He is enjoying it!"
            l "Cum until the very last drop of cum."
            "When she pulled off, it's like time started flowing once again in my dick."
            "Every accumulated urge of cumming was happening at once, it felt like a faucet was released and exploded."
            scene laura221 with dissolve
            l "Even given the circumstances, that's quite a big amount of cum."
            de "Wow, boss! Can I have a little bit taste of-"
            l "..."
            de "B-bad topic. You are completely covered, though. It's everywhere! Drippping off your body, even your pussy! And his dick is still dripping"
            p "Hah... Hah..."
            l "That's because he hasn't stop cumming."
            de "Amazing, I really want to-"
            l "You won't."
            de "R-right...! H-hehe...!"
            an "M-me too..."
            de "Tough luck, dummy, seems like the best we can do is watch."
            p "Hah... Hah... N-now... W-what...?"
            l "You are still not allowed to talk. And seems like this isn't over."
            p "W-what...?"
            l "You are truly amazing. Let's continue."

    scene black with fade
    "She continued doing the same for so long I lost track of time."
    "As always, the two idiots with her kept making remarks, ocassionally fighting with each other."
    "But Mom was just there, stoically milking me away over and over."
    "Even after cumming, as long as my dick was inside her, she kept milking me."
    "She sometimes pulled out off me to let me cum outside, but I kept doing it over and over. I was spent..."
    scene laura224 with dissolve
    $ clock.advance_hour()
    p "Hah... Hah...!"
    l "Hm, seems like it's almost over."
    an "Is he ok?"
    l "I swear, stop asking that."
    de "I'm willing to bet he enjoyed it plenty, and so have I! The splash zone was the best."
    an "You are covered in white goo..."
    de "And I love it!"
    p "W-why...? Hah..."
    l "I'm amazed, you can still talk. Doesn't matter, though. It is over."
    scene laura225 with dissolve
    "With an small plopping sound, mom pulled herself out of me completely."
    "Blobs of cum were everywhere, around the floor, and I'm sure Alma is covered in cum as well."
    "I can feel my cum dripping off mom's pussy as well... Just... Just how much have I cum?"
    "My dick is still tingling. It's completely covered in cum..."
    "My mind is hazy and everything is spinning around me..."
    de "Way to go, boss. He is completely dry!"
    an "Poor thing, he is shaking, his d-dick is shivering as well."
    l "He is not dry."
    de "You truly are an stud, handsome!"
    l "Don't call him that. I'm amazed he can still go on, but it's irrelevant."
    l "You are spent still, aren't you? Even when you don't feel tired, you can't even move, am I right?"
    l "It took me longer than I thought. But I said it before, this was just a warning."
    l "Don't come back, for your own good."
    p "W-wait...!"
    scene black with flash
    $ renpy.end_replay()
    p "Am I... Out...?"
    p "My head is throbbing... And the clock..."
    p "Not 24 hours yet!? Then how...!?"
    show eileen p41_serious with dissolve
    p "Eileen...? No way..."
    e "..."
    p "This can't be... How are you... Then mom is... She has something to do with all of this."
    e "... Maybe she is right. Maybe you should stop."
    p "No... Don't... You were the one that gave me this clock! I'm doing all of this for you!"
    e "If you keep going, you may not like where this will end."
    e p41_happy "But... Thanks, you have not give up. Yet."
    hide eileen with dissolve
    p "Not again! Wait!"
    $ inpsyche = False
    $ clock.hourclock = 2
    scene bg laura_hall with pflash
    show laura p13_surprised with pixellate
    l "H-honey...?"
    p "Hah..."
    l p13_surprised "Oh no... I knew it... I knew something was wrong..."
    l "Baby, please, are you ok...!?"
    p "Mom... I... I think I..."
    scene black with fade
    l "[povname]!"
    p "..."
    $ clock.advance_hour(2)
    scene bg laura_hall with fade
    p "..."
    p "I see, so I fainted..."
    p "What time is it?"
    p "S-shit...! It's already this late. W-where's mom..."
    p "Ah, right, I have a message from her in my phone. Let's see."
    l "Hi honey. I had to leave. I am so scared... I hope you wake up soon, I left you food on the table."
    l "When you wake up please let me know, I'm worried."
    p "... If you are so worried why did you leave me here by myself...?"
    p "Oh well, I should eat quickly and leave. I will let her know I'm ok once I finish, I'm starving."
    p "..."
    p "What a day."
    $ laura_second_day_finish = True
    scene black with logodissolve_laura
    jump day_end_laura
